### ISSUE TITLE
Linting:  extension_apis paths can lead to unclear bugs.  

### ISSUE THREAD

**Issue by gregglind** [mozilla/create-shield-study#13]
https://bugzilla.mozilla.org/show_bug.cgi?id=1496534

**Comment by pdehaan** [comment]
> The manifest.json syntax   for `experiment_apis.<thing>.paths` is easy to get wrong.
> 
> #### Correct Example:
> ```
>  "experiment_apis": {
>     "study": {
>       "schema": "./privileged/study/schema.json",
>       "parent": {
>         "scopes": ["addon_parent"],
>         "script": "./privileged/study/api.js",
>         "paths": [["study"], ["studyDebug"]]
>       }
>     }
>   },
> ```
> 
> #### Common Mistake:
> ```
>         "paths": ["study", "studyDebug"]
> ```
> 
> When run, this causes the dreaded "fun is not a function" error.  

&mdash; via Bugzilla link above

---

@gregglind Is there a schema or docs somewhere that explains the rules for `paths[]`?

Is it good enough to just assert that the `paths` array is just an array of single-element arrays? Or do the `["study"]` and `["studyDebug"]` keys links to other sections or have some other significance that we can also validate?
