### ISSUE TITLE
command not found: create-shield-study

### ISSUE THREAD

**Issue by pdehaan** [mozilla/create-shield-study#4]
When installing via `npx` or `npm init`, it looks like we cannot find the <kbd>create-shield-study</kbd> command.

### STR:

```sh
$ npm init mozilla/shield-study test1

npx: installed 1 in 5.46s
command not found: create-shield-study
```

I think we’re missing a `bin` command in the package.json. I tried fixing this in my branch, but am stuck with the following error:

> ./node_modules/.bin/plop: No such file or directory

I _believe_ this is because our ./create-shield-study bin file is using Bash, and the "plop" bin/command isn't in the path.
I tried fixing this using https://github.com/amwmedia/node-plop and https://github.com/taoyuan/ploper but never got very far.

**Comment by gregglind** [comment]
Good finds.

I think create-shield-study needs to published.  I want it to germinate a
little with your input before doing that.

**Comment by pdehaan** [comment]
I made some progress with **node-plop** in https://github.com/mozilla/create-shield-study/issues/5
