### ISSUE TITLE
Come up with a list of questions to ask in the create wizard

### ISSUE THREAD

**Issue by pdehaan** [mozilla/create-shield-study#6]
Per https://github.com/mozilla/create-shield-study/blob/master/plop-shield-study.js we currently have four prompts:

| # | NAME | MESSAGE
|--:|:-----|:--------
| 1. | `id` | webExtension id
| 2. | `xtype` | Shield (or Pioneer)
| 3. | `tellSI` | inform Strategy and Insights about your project
| 4. | `libraries` | choose all starting libraries

Not sure if we have any list of other candidates yet...

Possible ideas:

1. `name` &mdash; Used in manifest.json and package.json -- albeit for different reasons. manifest.json is more like a title, package.json is for the npm publishing name.
1. `version` &mdash; Or just default to 1.0.0 and let people hand tweak, if needed. Can be shared between package.json and manifest.json.
1. `description` &mdash; Seems like something that would be edited regularly. Can be shared between package.json and manifest.json.
1. `applications.gecko.id` &mdash; possibly a hyphenated, safe version of `name` (appended w/ "@shield.mozilla.org" or "@pioneer.mozilla.org", based on the `xtype` value). For manifest.json only.
1. `applications.gecko.strict_min_version` &mdash; Not sure how to do a sane default for this. For manifest.json only.
1. `author` &mdash; Either default to "Mozilla", or we can possibly try and be clever and extract from `npm config` defaults [1]. Can be shared between package.json and manifest.json.

Possibly others like `homepage_url` too, but probably better to err on the side of fewer prompts instead of a 19-step wizard.

---

<details>
<summary>[1] Using <b>npm-conf</b> to extract npm config's <code>author.name</code>, <code>author.email</code>, and <code>author.url</code>.</summary>

```js
const npmConf = require('npm-conf');

const conf = npmConf();

console.log("author.name:", conf.get("init.author.name"));
console.log("author.email:", conf.get("init.author.email"));
console.log("author.url:", conf.get("init.author.url"));
console.log("license:", conf.get("init.license"));
```
</details>

<details>
<summary>[2] Scraper for some recent Shield studies:</summary>

```js
#!/usr/bin/env node -r esm

import { stripIndent } from "common-tags";
import chalk from "chalk";
import got from "got";
// import manifests from "./manifest.json";

const manifests = [
  "https://raw.githubusercontent.com/mozilla/webcompat-blipz-experiment/master/webextension/manifest.json",
  "https://raw.githubusercontent.com/mozilla/blurts-addon/master/src/manifest.json",
  "https://raw.githubusercontent.com/mozilla/shield-studies-addon-utils/master/examples/small-study/src/manifest.json",
  "https://raw.githubusercontent.com/mozilla/shield-studies-addon-template/master/src/manifest.json",
  "https://raw.githubusercontent.com/motin/taar-experiment-v3-shield-study/develop/src/manifest.json",
  "https://raw.githubusercontent.com/florian/federated-learning-addon/master/manifest.json",
  "https://raw.githubusercontent.com/mozilla/shield-cloudstorage/master/webextension/manifest.json"
];

const label = (str) => chalk.bold(str);

async function main() {
  manifests.forEach(async uri => {
    const { body } = await got(uri, { json: true });

    console.log(stripIndent`
      ${chalk.blue(repo(uri))}
        ${label("name:")} ${body.name}
        ${label("description:")} ${body.description}
        ${label("version:")} ${body.version}
        ${label("author:")} ${body.author}
        ${label("applications.gecko.id:")} ${body.applications.gecko.id}
        ${label("applications.gecko.strict_min_version:")} ${body.applications.gecko.strict_min_version}
    `);
    console.log("");
  });
}

main();

function repo(uri) {
  return uri.replace(/^https:\/\/.*?\/(.*?)\/(.*?)\/.*$/, "https://github.com/$1/$2");
}
```

```
https://github.com/mozilla/webcompat-blipz-experiment
  name: __MSG_addonName__
  description: __MSG_addonDescription__
  version: 1.0.0
  author: __MSG_addonAuthorsList__
  applications.gecko.id: webcompat-blipz-experiment@shield.mozilla.org
  applications.gecko.strict_min_version: undefined

https://github.com/mozilla/shield-studies-addon-template
  name: Button Icon Preference - Shield Study Example
  description: __MSG_extensionDescription__
  version: 2.0.0
  author: undefined
  applications.gecko.id: button-icon-preference@shield.mozilla.org
  applications.gecko.strict_min_version: 61.0a1

https://github.com/florian/federated-learning-addon
  name: Federated Learning Awesome Bar
  description: Improve history and bookmark search
  version: 1.0.2
  author: undefined
  applications.gecko.id: federated-learning@shield.mozilla.org
  applications.gecko.strict_min_version: undefined

https://github.com/motin/taar-experiment-v3-shield-study
  name: TAAR v3 (Telemetry-Aware Addon Recommender)
  description: __MSG_extensionDescription__
  version: 3.0.3
  author: undefined
  applications.gecko.id: taarexpv3@shield.mozilla.org
  applications.gecko.strict_min_version: 60.0.1

https://github.com/mozilla/blurts-addon
  name: Firefox Monitor
  description: undefined
  version: 2.4
  author: undefined
  applications.gecko.id: fxmonitor@mozilla.org
  applications.gecko.strict_min_version: 62.0

https://github.com/mozilla/shield-cloudstorage
  name: Cloud Storage Shield Study Web Extension Experiment (CSSSWEE)
  description: Cloud Storage Shield study as WebExtension Experiments
  version: 1.0.1
  author: Mozilla (https://mozilla.org/)
  applications.gecko.id: cloudstorage-webextensionExperiment@shield.mozilla.org
  applications.gecko.strict_min_version: 60.0

https://github.com/mozilla/shield-studies-addon-utils
  name: A Small Shield Add-on
  description: Demo of shield-studies-addon-utils
  version: 1.0.0
  author: undefined
  applications.gecko.id: shield-utils-small-study-demo@shield.mozilla.org
  applications.gecko.strict_min_version: 60.0
```
</details>

**Comment by gregglind** [comment]
* bug number

**Comment by pdehaan** [comment]
Re: `applications.gecko.strict_min_version`, somebody pointed me to https://product-details.mozilla.org/1.0/firefox_versions.json, which is currently:

```js
{
  FIREFOX_ESR: "60.2.2esr",
  FIREFOX_ESR_NEXT: "",
  LATEST_FIREFOX_VERSION: "62.0.3",
  FIREFOX_DEVEDITION: "63.0b11",
  LATEST_FIREFOX_DEVEL_VERSION: "63.0b11",
  LATEST_FIREFOX_RELEASED_DEVEL_VERSION: "63.0b11",
  FIREFOX_AURORA: "",
  FIREFOX_NIGHTLY: "64.0a1",
  LATEST_FIREFOX_OLDER_VERSION: "3.6.28",
}
```


**UPDATE:** :pmac also pointed me to https://github.com/mozilla/product-details-json/blob/master/product-details/firefox_versions.json which is a GitHub hosted version of the file, but seems to mirror what is on the product-details.mozilla.org site.

So I think the next step for `applications.gecko.strict_min_version` (if we want to add it to the wizard) would be to try fetching the remote JSON blob, extracting the `LATEST_FIREFOX_VERSION` ("62.0.3"), `FIREFOX_DEVEDITION` ("63.0b11"), and `FIREFOX_NIGHTLY` ("64.0a1") keys and using those in the prompt. If those seem too specific, we could possibly parse them first to simplify to "62.0", "63.0", and "64.0" and see if those version strings still pass the `web-ext lint` linter rules.
