### ISSUE TITLE
What should 'tell S+I do'?

### ISSUE THREAD

**Issue by gregglind** [mozilla/create-shield-study#8]

**Comment by gregglind** [comment]
- email / mailto
- print to command line
- slack thing
- github ... needs tokens

**Comment by pdehaan** [comment]
Another option we discussed was something like https://github.com/sindresorhus/opn

```js
const opn = require("opn");

opn("mailto:pdehaan@mozilla.com");
```

But it seems to open my Mail.app on macOS (which I don't use), but that's the same behavior as using <kbd>open mailto:pdehaan@mozilla.com</kbd> on the CLI so I probably haven't set up my protocol associations yet.

**Comment by pdehaan** [comment]
Another idea I had in a different bug comment, was we could create a new repo speifically for issues/notifications. Then we can use **opn** to redirect users to the __github.com/mozilla/{{repoName}}/issues/new__ page, and either use the GitHub new issue template to prefill in the body with information we want to collect, or we could also specify the bug title, body, labels as query parameters, a'la `.../issues/new?title=some+safe+title&body=Oh+boy+this+may+be+long`
